import { NgModule } from '@angular/core';
import {
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatDialogModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSidenavModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatExpansionModule,
} from '@angular/material';

@NgModule({
    declarations: [],
    imports: [
        MatButtonModule,
        MatCardModule,
        MatRadioModule,
        MatInputModule,
        MatSelectModule,
        MatCheckboxModule,
        MatIconModule,
        MatDialogModule,
        MatToolbarModule,
        MatSidenavModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatMenuModule,
        MatListModule,
        MatExpansionModule,
    ],
    exports: [
        MatButtonModule,
        MatCardModule,
        MatRadioModule,
        MatInputModule,
        MatSelectModule,
        MatCheckboxModule,
        MatIconModule,
        MatDialogModule,
        MatToolbarModule,
        MatSidenavModule,
        MatSnackBarModule,
        MatProgressSpinnerModule,
        MatMenuModule,
        MatListModule,
        MatExpansionModule,
    ],
})
export class MaterialModule {}
